#!/usr/bin/env python3
"""Generate 38 RANS campaign config files and a job list for SLURM array submission.

Flow cases:
    cylinder_re100, airfoil_re1000, step_re5000, hills_re10595

Turbulence models:
    9 standard models for all cases + 2 extra (nn hills-specific presets) for hills only.

Output:
    examples/13_rans_campaign/*.cfg   (38 config files)
    scripts/rans_campaign/job_list.txt (array-index -> executable + config mapping)
"""

import os
import sys

# ---------------------------------------------------------------------------
# Flow-case definitions
# ---------------------------------------------------------------------------

FLOW_CASES = {
    "cylinder_re100": {
        "exe": "cylinder",
        "params": {
            "Nx": 192, "Ny": 128, "Nz": 4,
            "x_min": 0.0, "x_max": 30.0,
            "y_min": -10.0, "y_max": 10.0,
            "z_min": 0.0, "z_max": 3.14159,
            "nu": 0.01, "dp_dx": 0.0,
            "bulk_velocity_target": 1.0,
            "max_steps": 50000, "CFL_max": 0.3,
            "adaptive_dt": "true",
            "simulation_mode": "unsteady",
            "convective_scheme": "upwind2",
            "poisson_solver": "auto",
            "poisson_tol": 1e-6,
            "poisson_max_vcycles": 20,
            "output_freq": 500,
            "write_fields": "true",
            "num_snapshots": 10,
        },
    },
    "airfoil_re1000": {
        "exe": "airfoil",
        "params": {
            "Nx": 512, "Ny": 256, "Nz": 4,
            "x_min": -2.0, "x_max": 6.0,
            "y_min": -4.0, "y_max": 4.0,
            "z_min": 0.0, "z_max": 1.0,
            "nu": 0.001, "dp_dx": 0.0,
            "bulk_velocity_target": 1.0,
            "max_steps": 50000, "CFL_max": 0.3,
            "adaptive_dt": "true",
            "simulation_mode": "unsteady",
            "convective_scheme": "upwind2",
            "poisson_solver": "auto",
            "poisson_tol": 1e-6,
            "poisson_max_vcycles": 20,
            "output_freq": 500,
            "write_fields": "true",
            "num_snapshots": 10,
        },
    },
    "step_re5000": {
        "exe": "step",
        "params": {
            "Nx": 256, "Ny": 128, "Nz": 4,
            "x_min": -10.0, "x_max": 20.0,
            "y_min": 0.0, "y_max": 6.0,
            "z_min": 0.0, "z_max": 1.0,
            "nu": 0.0002, "dp_dx": 0.0,
            "bulk_velocity_target": 1.0,
            "max_steps": 50000, "CFL_max": 0.3,
            "adaptive_dt": "true",
            "simulation_mode": "unsteady",
            "convective_scheme": "upwind2",
            "poisson_solver": "multigrid",
            "poisson_tol": 1e-6,
            "poisson_max_vcycles": 20,
            "output_freq": 500,
            "write_fields": "true",
            "num_snapshots": 10,
        },
    },
    "hills_re10595": {
        "exe": "hills",
        "params": {
            "Nx": 192, "Ny": 96, "Nz": 4,
            "x_min": 0.0, "x_max": 9.0,
            "y_min": 0.0, "y_max": 3.035,
            "z_min": 0.0, "z_max": 1.0,
            "nu": 9.438e-5, "dp_dx": -1.0,
            "max_steps": 50000, "CFL_max": 0.3,
            "adaptive_dt": "true",
            "simulation_mode": "unsteady",
            "convective_scheme": "upwind2",
            "poisson_solver": "auto",
            "poisson_tol": 1e-6,
            "poisson_max_vcycles": 20,
            "output_freq": 500,
            "write_fields": "true",
            "num_snapshots": 10,
        },
    },
}

# ---------------------------------------------------------------------------
# Turbulence model definitions
# ---------------------------------------------------------------------------

# Standard models applied to all 4 flow cases
STANDARD_MODELS = [
    {"name": "baseline",   "turb_model": "baseline"},
    {"name": "komega",     "turb_model": "komega"},
    {"name": "sst",        "turb_model": "sst"},
    {"name": "gep",        "turb_model": "gep"},
    {"name": "earsm_wj",   "turb_model": "earsm_wj"},
    {"name": "earsm_gs",   "turb_model": "earsm_gs"},
    {"name": "earsm_pope", "turb_model": "earsm_pope"},
    {"name": "nnmlp",      "turb_model": "nn_mlp",  "nn_preset": "mlp_channel_caseholdout"},
    {"name": "nntbnn",     "turb_model": "nn_tbnn", "nn_preset": "tbnn_channel_caseholdout"},
]

# Extra models for hills_re10595 only
HILLS_EXTRA_MODELS = [
    {"name": "nnmlp",  "suffix": "_phll", "turb_model": "nn_mlp",  "nn_preset": "mlp_phll_caseholdout"},
    {"name": "nntbnn", "suffix": "_phll", "turb_model": "nn_tbnn", "nn_preset": "tbnn_phll_caseholdout"},
]


def write_config(filepath, case_params, model_dict, output_dir):
    """Write a single INI-style .cfg file."""
    with open(filepath, "w") as f:
        f.write("# Auto-generated by generate_configs.py\n")
        f.write("# RANS validation campaign\n\n")

        # Grid
        f.write("# Grid\n")
        for key in ("Nx", "Ny", "Nz"):
            f.write(f"{key} = {case_params[key]}\n")

        # Domain
        f.write("\n# Domain\n")
        for key in ("x_min", "x_max", "y_min", "y_max", "z_min", "z_max"):
            f.write(f"{key} = {case_params[key]}\n")

        # Physics
        f.write("\n# Physics\n")
        f.write(f"nu = {case_params['nu']}\n")
        f.write(f"dp_dx = {case_params['dp_dx']}\n")
        if "bulk_velocity_target" in case_params:
            f.write(f"bulk_velocity_target = {case_params['bulk_velocity_target']}\n")

        # Turbulence
        f.write("\n# Turbulence model\n")
        f.write(f"turb_model = {model_dict['turb_model']}\n")
        if "nn_preset" in model_dict:
            f.write(f"nn_preset = {model_dict['nn_preset']}\n")

        # Time stepping
        f.write("\n# Time stepping\n")
        f.write(f"max_steps = {case_params['max_steps']}\n")
        f.write(f"CFL_max = {case_params['CFL_max']}\n")
        f.write(f"adaptive_dt = {case_params['adaptive_dt']}\n")
        f.write(f"simulation_mode = {case_params['simulation_mode']}\n")
        f.write(f"convective_scheme = {case_params['convective_scheme']}\n")

        # Poisson solver
        f.write("\n# Poisson solver\n")
        f.write(f"poisson_solver = {case_params['poisson_solver']}\n")
        f.write(f"poisson_tol = {case_params['poisson_tol']}\n")
        f.write(f"poisson_max_vcycles = {case_params['poisson_max_vcycles']}\n")

        # Output
        f.write("\n# Output\n")
        f.write(f"output_freq = {case_params['output_freq']}\n")
        f.write(f"write_fields = {case_params['write_fields']}\n")
        f.write(f"num_snapshots = {case_params['num_snapshots']}\n")
        f.write(f"output_dir = {output_dir}\n")


def main():
    # Resolve project root (two levels up from this script)
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.normpath(os.path.join(script_dir, "..", ".."))

    config_dir = os.path.join(project_root, "examples", "13_rans_campaign")
    job_list_path = os.path.join(script_dir, "job_list.txt")

    os.makedirs(config_dir, exist_ok=True)

    jobs = []  # (exe, config_relative_path)
    generated = 0

    for case_name, case_def in FLOW_CASES.items():
        exe = case_def["exe"]
        params = case_def["params"]

        # Standard models
        for model in STANDARD_MODELS:
            suffix = model.get("suffix", "")
            cfg_name = f"{case_name}_{model['name']}{suffix}.cfg"
            cfg_path = os.path.join(config_dir, cfg_name)
            basename = cfg_name.replace(".cfg", "")
            output_dir = f"output/rans_campaign/{basename}/"

            write_config(cfg_path, params, model, output_dir)
            jobs.append((exe, f"examples/13_rans_campaign/{cfg_name}"))
            generated += 1

        # Extra hills models
        if case_name == "hills_re10595":
            for model in HILLS_EXTRA_MODELS:
                suffix = model.get("suffix", "")
                cfg_name = f"{case_name}_{model['name']}{suffix}.cfg"
                cfg_path = os.path.join(config_dir, cfg_name)
                basename = cfg_name.replace(".cfg", "")
                output_dir = f"output/rans_campaign/{basename}/"

                write_config(cfg_path, params, model, output_dir)
                jobs.append((exe, f"examples/13_rans_campaign/{cfg_name}"))
                generated += 1

    # Write job list
    with open(job_list_path, "w") as f:
        f.write("# index  executable  config_path\n")
        for idx, (exe, cfg_rel) in enumerate(jobs):
            f.write(f"{idx} {exe} {cfg_rel}\n")

    print(f"Generated {generated} config files in {config_dir}")
    print(f"Job list written to {job_list_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
